samples:
  - "13_7"
  - "A1602"
  - "AF2019"
  - "ATCC_8042"
  - "BB22-4M"
  - "BCC1"
  - "CACC_537"
  - "CITKHZ7"
  - "CLP03"
  - "F1493"
  - "FDAARGOS_1007"
  - "FDAARGOS_1008"
  - "FDAARGOS_1133"
  - "GLP06"
  - "HN9"
  - "IAF5919"
  - "IAF6519"
  - "JQII-5"
  - "loliI_FS10"
  - "MT25"
  - "P72N"
  - "PA_ZFRA1"
  - "PA_ZFRFD"
  - "PB22"
  - "pll"
  - "PMC48"
  - "PMC65"
  - "PMC202"
  - "SRCM100313"
  - "SRCM100424"
  - "SRCM101189"
  - "SRCM102024"
  - "SRCM102731"
  - "SRCM102732"
  - "SRCM103367"
  - "SRCM103387"
  - "SRCM103444"
  - "TCI188"
  - "WT_1"
  - "XJ-24"
  - "ZPA017"
  - "ZY271"
